name: light-it-2
version: "3.8"

services:
    db:
        image: postgres:15
        container_name: laravel-postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
        driver: local
